stages:
  convert_labeled_data:
    cmd: python src/convert_labeled_data.py
    deps:
    - data/labeled_data.csv
    - src/convert_labeled_data.py
    outs:
    - data/annotation_per_row_data.csv
  fetch_labeled_data:
    cmd: ./src/fetch_data.sh
    deps:
    - src/fetch_data.sh
    outs:
    - data/labeled_data.csv
  download_audio:
    cmd: python ./src/download_audio.py --target-dir data/audio --annotations-file
      data/annotation_per_row_data.csv
    deps:
    - data/annotation_per_row_data.csv
    - src/download_audio.py
    outs:
    - data/audio
  extract_data_quality:
    cmd: python ./src/extract_data_quality.py
    deps:
    - data/annotation_per_row_data.csv
    - src/extract_data_quality.py
    outs:
    - data/data_quality/sample_based_quality.json
    - data/data_quality/samples_per_label.csv
  cut_in_chunks:
    cmd: python src/cut_in_chunks.py
    deps:
    - data/annotation_per_row_data.csv
    - src/cut_in_chunks.py
    params:
    - chunk_size
    - chunk_overlap
    outs:
    - data/chunked_data.csv
  balance_data_set:
    cmd: python src/balance_dataset.py
    deps:
    - data/chunked_data.csv
    - src/balance_dataset.py
    outs:
    - data/balanced_data.csv
  extract_features:
    cmd: python src/extract_mfcc_features.py
    deps:
    - data/balanced_data.csv
    - data/audio
    - src/extract_mfcc_features.py
    params:
    - feature_extraction
    outs:
    - ./data/mffc_data.h5
  train_model:
    cmd: python src/train_xgboost.py
    deps:
    - data/mffc_data.h5
    - src/train_xgboost.py
    params:
    - model
    outs:
    - models/xgboost_model.json

metrics:
- data/data_quality/sample_based_quality.json
- data/data_quality/chunk_balanced_quality.json
- dvclive/metrics.json
plots:
- number of samples vs label:
    template: bar_horizontal_sorted
    x: '0'
    y:
      data/data_quality/samples_per_label.csv: label

- dvclive/plots/metrics:
    x: step
- dvclive/plots/sklearn/confusion_matrix.json:
    template: confusion
    x: actual
    y: predicted
    title: Confusion Matrix
    x_label: True Label
    y_label: Predicted Label
params:
- params.yaml
