stages:
  convert_labeled_data:
    cmd: python src/convert_labeled_data.py
    deps:
    - data/labeled_data.csv
    - src/convert_labeled_data.py
    outs:
    - data/annotation_per_row_data.csv
  fetch_labeled_data:
    cmd: ./src/fetch_data.sh
    deps:
    - src/fetch_data.sh
    outs:
    - data/labeled_data.csv
  download_audio:
    cmd: python ./src/download_audio.py --target-dir data/audio --annotations-file
      data/annotation_per_row_data.csv
    deps:
    - data/annotation_per_row_data.csv
    - src/download_audio.py
    outs:
    - data/audio
