chunk_size: 500 # ms
chunk_overlap: 30 #ms
inbalance_ratio: 1.0 # How much more background samples should be drawn

feature_extraction:
  n_mfcc: 13
  n_fft: 512

training:
  test_size: 0.2

model:
  n_estimators: 25
  max_depth: 6
  learning_rate: 0.1
  random_state: 42
